name: Build VLCKit SPM

on:
  push:
    tags:
      - '3.6.*'
      - 'v3.6.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
        
    - name: Setup Git LFS
      run: |
        git lfs install
        git lfs pull
        
    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods
        pod --version
        
    - name: Download MobileVLCKit
      run: ./build-scripts/download-mobilevlckit.sh
      
    - name: Verify XCFramework
      run: |
        if [ -d "VLCKit.xcframework" ]; then
          echo "✅ XCFramework created successfully"
          echo "Size: $(du -sh VLCKit.xcframework | cut -f1)"
          
          # Test framework can be loaded
          xcodebuild -version
          echo "XCFramework info:"
          find VLCKit.xcframework -name "Info.plist" -exec cat {} \;
        else
          echo "❌ XCFramework not found"
          exit 1
        fi
        
    - name: Create Release Archive
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        zip -r VLCKit.xcframework.zip VLCKit.xcframework
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          VLCKit.xcframework.zip
        body: |
          ## VLCKit SPM ${{ github.ref_name }}
          
          Swift Package Manager distribution of MobileVLCKit 3.6.0
          
          ### What's Included
          - Complete MobileVLCKit 3.6.0 APIs
          - iOS/tvOS support (iOS 11+, tvOS 11+)
          - Universal XCFramework (~200MB)
          
          ### Installation
          Add to your Package.swift:
          ```swift
          .package(url: "https://github.com/rsaleass/VLCKit-SPM", from: "${{ github.ref_name }}")
          ```
          
          ### Verification
          Built from official MobileVLCKit 3.6.0 CocoaPods distribution.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}